spring.application.name=ChamadoServicoCondominio

# Configurações do banco de dados
spring.datasource.url=jdbc:postgresql://localhost:5432/mydatabase
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=myuser
spring.datasource.password=secret

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.flyway.baseline-on-migrate=true
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

logging.level.org.springframework.security=DEBUG

api.security.jwt.secret=${JWT_SECURITY:mysecretkey}
api.security.jwt.expiration-hours= 1
